# Generated by Django 4.2.1 on 2023-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_app_id_user_cert_id_user_dev_id_user_ebay_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ebay_token',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='ebay Token'),
        ),
    ]
